# 应用名称
spring:
  application:
    name: mowang-shop-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848 #Nacos作为配置中心地址
        file-extension: yml #指定yml格式的配置
        namespace: third-party
    alicloud:
      access-key: LTAI5tDLhC6BNQ9M87qYwEq2
      secret-key: 8cTCIQ2txblQA7FguCAQmgIzSKZZ0B
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: mowang-shop

server:
  port: 9527

