spring:
  application:
    name: mowang-shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848 #Nacos作为配置中心地址
        file-extension: yml #指定yml格式的配置
        namespace: gateway
    gateway:
      routes:
        - id: product_route
          uri: lb://mowang-shop-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://mowang-shop-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware_route
          uri: lb://mowang-shop-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://mowang-shop-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}
        - id: admin_route
          uri: lb://admin # 路由给renren-fast，lb代表负载均衡
          predicates: # 什么情况下路由给它
            - Path=/api/** # 默认前端项目都带上api前缀，
          filters:
            - RewritePath=/api/(?<segment>.*),/admin/$\{segment}

server:
  port: 88